# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.5-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - run:
          name: checkout
          command: |
            mkdir -p ~/.ssh
            echo "Host *" > ~/.ssh/config
            echo " StrictHostKeyChecking no" >> ~/.ssh/config
            git --version
            git clone -b build git@github.com:kalug/kalug.git ~/repo
            git worktree add content origin/master -b master
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "requirements.txt" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-
#      - save_cache:
#          paths:
#            - ./venv
#          key: v1-dependencies-{{ checksum "requirements.txt" }}


      - run:
          name: run build
          command: |
            git --version
            git config --global user.name "CI"
            git config --global user.email "circleci@kalug.linux.org.tw"
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            ./rss2md.py
            wget https://github.com/gohugoio/hugo/releases/download/v0.41/hugo_0.41_Linux-64bit.tar.gz
            pushd venv/bin
              tar zxvf ../../hugo_0.41_Linux-64bit.tar.gz
            popd
            git clone git@github.com:kalug/kalug.github.io.git public

            hugo
      - run:
          name: run push master (content)
          command: |
            pushd content
            git add .
            git commit -m "platnet update" || true
            git push origin master || true
            popd
      - run:
          name: run push kalug.github.io
          command: |
            pushd public
            git add .
            git commit -m "ci update" || true
            git push origin master || true
            popd
general:
  branches:
    only:
      - master # content & circle ci - config
